# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.BigIntegerField()),
                ('recommendations', models.TextField()),
            ],
        ),
    ]
