# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationset',
            name='source',
            field=models.CharField(default='cpa', max_length=3),
            preserve_default=False,
        ),
    ]
