# Generated by Django 3.0.5 on 2020-04-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_experiment_feedback_item_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('seed_item', 'rank', 'source')},
        ),
    ]
